# Generated by Django 5.0.6 on 2026-05-28 09:20

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Income',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('income_type', models.CharField(choices=[('salary', '💼 Salary'), ('freelance', '💻 Freelance / Side Work'), ('field_expense', '🧾 Field Expense (Reimbursable)'), ('business', '🏢 Business Income'), ('investment', '📈 Investment Returns'), ('other', '📦 Other')], default='salary', max_length=30)),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('notes', models.TextField(blank=True)),
                ('is_recurring', models.BooleanField(default=False, help_text='Monthly recurring income')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-date', '-created_at'],
            },
        ),
    ]
