# Generated by Django 5.0.6 on 2026-05-28 09:52

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0002_income'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='savingsaccount',
            name='interest_rate',
        ),
        migrations.RemoveField(
            model_name='savingsaccount',
            name='target',
        ),
        migrations.AddField(
            model_name='savingsaccount',
            name='bank_name',
            field=models.CharField(blank=True, help_text='e.g. KCB, Equity, NCBA', max_length=200),
        ),
        migrations.AddField(
            model_name='savingsaccount',
            name='linked_goal',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='savings_accounts', to='finance.goal'),
        ),
        migrations.AddField(
            model_name='savingsaccount',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='savingsaccount',
            name='emoji',
            field=models.CharField(default='🏦', max_length=10),
        ),
        migrations.CreateModel(
            name='SavingsBalanceHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('balance', models.DecimalField(decimal_places=2, max_digits=12)),
                ('notes', models.CharField(blank=True, max_length=300)),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='history', to='finance.savingsaccount')),
            ],
            options={
                'ordering': ['-date', '-created_at'],
            },
        ),
        migrations.DeleteModel(
            name='SavingsTransaction',
        ),
    ]
