# Generated by Django 5.0.6 on 2026-05-28 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0003_remove_savingsaccount_interest_rate_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='savingsbalancehistory',
            name='amount_saved',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Amount saved this month/period', max_digits=12),
        ),
        migrations.AlterField(
            model_name='savingsbalancehistory',
            name='balance',
            field=models.DecimalField(decimal_places=2, help_text='Total balance at this point', max_digits=12),
        ),
    ]
