# Generated by Django 5.0.6 on 2026-05-28 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0004_savingsbalancehistory_amount_saved_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='savingsbalancehistory',
            name='account',
        ),
        migrations.CreateModel(
            name='MonthlySaving',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField(default=2025)),
                ('month', models.IntegerField(choices=[(1, 'January'), (2, 'February'), (3, 'March'), (4, 'April'), (5, 'May'), (6, 'June'), (7, 'July'), (8, 'August'), (9, 'September'), (10, 'October'), (11, 'November'), (12, 'December')], default=1)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('notes', models.CharField(blank=True, max_length=300)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-year', '-month'],
                'unique_together': {('year', 'month')},
            },
        ),
        migrations.DeleteModel(
            name='SavingsAccount',
        ),
        migrations.DeleteModel(
            name='SavingsBalanceHistory',
        ),
    ]
