# Generated by Django 5.0.6 on 2026-05-28 14:57

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0005_remove_savingsbalancehistory_account_monthlysaving_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Debt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('debt_type', models.CharField(choices=[('loan', '🏦 Bank / SACCO Loan'), ('credit_card', '💳 Credit Card'), ('bnpl', '🛒 Buy Now Pay Later'), ('personal', '🤝 Personal Debt'), ('mobile_loan', '📱 Mobile Loan (Fuliza / M-Shwari)'), ('other', '📦 Other')], default='loan', max_length=20)),
                ('emoji', models.CharField(default='💳', max_length=10)),
                ('total_amount', models.DecimalField(decimal_places=2, help_text='Original loan amount', max_digits=12)),
                ('remaining_balance', models.DecimalField(decimal_places=2, help_text='Current outstanding balance', max_digits=12)),
                ('monthly_payment', models.DecimalField(decimal_places=2, default=0, help_text='Expected monthly payment', max_digits=10)),
                ('interest_rate', models.DecimalField(decimal_places=2, default=0, help_text='Annual interest rate %', max_digits=5)),
                ('due_date', models.DateField(blank=True, help_text='Final repayment date', null=True)),
                ('lender', models.CharField(blank=True, help_text='e.g. KCB, Equity, friend name', max_length=200)),
                ('notes', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='DebtPayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('notes', models.CharField(blank=True, max_length=300)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('debt', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='finance.debt')),
            ],
            options={
                'ordering': ['-date', '-created_at'],
            },
        ),
    ]
